parameters:
    c2is.social_wall.class: C2iS\SocialWall\SocialWall
    c2is.social_wall.manager.class: C2is\Bundle\SocialWallBundle\Manager\SocialWallManager
    c2is.social_wall.cache_provider.class: C2iS\SocialWall\Cache\FileCacheProvider

services:
    c2is.social_wall:
        class: %c2is.social_wall.class%
        arguments: [%c2is_social_wall%]
    c2is.social_wall.manager:
        class: %c2is.social_wall.manager.class%
        arguments: ["@c2is.social_wall", "@c2is.social_wall.cache_provider", %c2is_social_wall%]
    c2is.social_wall.cache_provider:
        class: %c2is.social_wall.cache_provider.class%
        arguments: ['%kernel.cache_dir%/socialwall/', %c2is_social_wall.cache.duration%]
    c2is.social_wall.orm_metadata_subscriber:
        class: C2is\Bundle\SocialWallBundle\EventListener\ORMMetadataSubscriber
        arguments: [%c2is_social_wall.model_configuration%]
        tags:
            - { name: doctrine.event_subscriber, priority: 8192 }
    c2is.social_wall.transformer.social_item:
        class: C2is\Bundle\SocialWallBundle\Transformer\SocialItemTransformer
