C2is\Bundle\SocialWallBundle\Model\SocialUser:
    type: mappedSuperclass
    table: social_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        socialId:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 255
            nullable: true
        link:
            type: string
            length: 2000
            nullable: true
    oneToMany:
        items:
            targetEntity: C2is\Bundle\SocialWallBundle\Model\SocialItem
            mappedBy: user
    oneToOne:
        image:
            targetEntity: C2is\Bundle\SocialWallBundle\Model\Media
            cascade: ["persist", "merge"]
            joinColumn:
                name: social_media_id
                referencedColumnName: id
                onDelete: CASCADE
