C2is\Bundle\SocialWallBundle\Model\Tag:
    type: mappedSuperclass
    table: social_tag
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        link:
            type: string
            length: 2000
            nullable: true
    manyToMany:
        items:
            targetEntity: C2is\Bundle\SocialWallBundle\Model\SocialItem
            mappedBy: tags
